### ISSUE TITLE
Create concat task

### ISSUE THREAD

**Issue by ngocsangyem** [coderiver/generator-man#72]
Hi ! 
Is there anyway to create concat file?

**Comment by akella** [comment]
Hi! What exactly do you mean? To concat what?

**Comment by ngocsangyem** [comment]
Hi @akella ! I want to concat js file from bower and npm package

**Comment by akella** [comment]
But webpack does that, why do you need a concat? 
There is also task where you can manually concatenate files https://monosnap.com/file/T6gAUgjTwbUm0bMYVZGanDFkqkhiL7

**Comment by ngocsangyem** [comment]
@akella Sorry ! I am a starter , webpack is new for me :(

**Comment by akella** [comment]
That's alright, we've all been there.
Webpack is what you want, it will concatenate all in one module.

**Comment by ngocsangyem** [comment]
how i can manually webpack to concat js files

**Comment by akella** [comment]
Check out examplr in the project with sayHello.js, it concatenates it into app.js

**Comment by ngocsangyem** [comment]
Thank you :D

**Comment by akella** [comment]
No problem! =)
