### ISSUE TITLE
Если выбирать pug, то все равно остаются задачи для nunjucks в gulpfile.babel.js

### ISSUE THREAD

**Issue by F-y-o-d-o-r** [coderiver/generator-man#75]
https://github.com/coderiver/generator-man/blob/6aa630d06d89f597aeff518f9a4b919c19aa1c35/generators/app/templates/gulpfile.babel.js#L14
стоит
gulp.task('nunjucks', () => getTaskBuild('nunjucks'));
gulp.task('nunjucks:watch', getTaskWatch('nunjucks'));
вместо
gulp.task('pug', () => getTaskBuild('pug'));
gulp.task('pug:watch', getTaskWatch('pug'));
Спасибо за удобный инструмент!
:thumbsup:

**Comment by akella** [comment]
Спасибо! Еще не успел PUG проверить, обновлю.
